<?php

/**
 * table_name => Laravel connection name (must match config/database.php).
 * Keep in sync with INSERT rows in database/scripts/split-databases.sql.
 */
return [
    'users' => 'auth_db',
    'password_reset_tokens' => 'auth_db',
    'sessions' => 'auth_db',
    'user_verifications' => 'auth_db',
    'staff_invites' => 'auth_db',
    'staff_teams' => 'auth_db',
    'staff_team_members' => 'auth_db',
    'staff_documents' => 'auth_db',
    'visits' => 'pii_db',
    'newsletter_subscribers' => 'pii_db',
    'support_conversation_reads' => 'pii_db',
    'coach_profiles' => 'pii_db',
    'coach_verification_documents' => 'kyc_db',
    'agent_absence_requests' => 'kyc_db',
    'agent_absence_request_files' => 'kyc_db',
    'payments' => 'payments_db',
    'refunds' => 'payments_db',
    'payouts' => 'payments_db',
    'payout_runs' => 'payments_db',
    'payout_batches' => 'payments_db',
    'wallet_transactions' => 'payments_db',
    'coach_withdrawals' => 'payments_db',
    'coach_payout_methods' => 'payments_db',
    'coach_payout_accounts' => 'payments_db',
    'coach_payouts' => 'payments_db',
    'coach_payout_items' => 'payments_db',
    'booking_fees' => 'payments_db',
    'service_fees' => 'payments_db',
    'disputes' => 'payments_db',
    'dispute_summaries' => 'payments_db',
    'services' => 'app_db',
    'service_categories' => 'app_db',
    'service_packages' => 'app_db',
    'service_faqs' => 'app_db',
    'service_favorites' => 'app_db',
    'coach_favorites' => 'app_db',
    'reservations' => 'app_db',
    'reservation_slots' => 'app_db',
    'reservation_reviews' => 'app_db',
    'coach_weekly_hours' => 'app_db',
    'coach_unavailabilities' => 'app_db',
    'coach_availability_overrides' => 'app_db',
    'site_settings' => 'app_db',
    'conversations' => 'comms_db',
    'messages' => 'comms_db',
    'support_conversations' => 'comms_db',
    'support_messages' => 'comms_db',
    'support_conversation_ratings' => 'comms_db',
    'support_questions' => 'comms_db',
    'support_question_messages' => 'comms_db',
    'support_question_acknowledgements' => 'comms_db',
    'staff_chat_rooms' => 'comms_db',
    'staff_chat_room_users' => 'comms_db',
    'staff_chat_attachments' => 'media_db',
    'admin_action_logs' => 'audit_db',
    'admin_security_events' => 'audit_db',
    'staff_deletion_audits' => 'audit_db',
    'agent_absence_audits' => 'audit_db',
    'agent_status_logs' => 'audit_db',
    'staff_dm_threads' => 'audit_db',
    'staff_dm_messages' => 'audit_db',
    'staff_chat_messages' => 'audit_db',
    'analytics_events' => 'audit_db',
    'dispute_messages' => 'audit_db',
    'dispute_attachments' => 'audit_db',
    'cache' => 'audit_db',
    'cache_locks' => 'audit_db',
    'jobs' => 'audit_db',
    'job_batches' => 'audit_db',
    'failed_jobs' => 'audit_db',
];
